server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:6609/zyzcfb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: zyzcfb
    password: XingHuo@1988_ZYZCFB

  jpa:
    open-in-view: false